### PR TITLE
Added Contributing  Code of conduct markdown files

### LINKED ISSUE #3: Add CONTRIBUTING.md and CODE_OF_CONDUCT.md
In the spirit of getting more contributors to the project, the above documents would be appreciated.

### PR DESCRIPTION
**Pull request by DanBrown47**

### CODE REVIEW

**Comment by gridhead** [comment]
Hi @DanBrown47, thanks for taking time to contribute to the project! You are requested to first register at http://organize.mlh.io/participants/events/4659-hack-astrosonic our Hacktoberfest event to stay connected throughout the contribution period.

There are certain things I would want to note before beginning the review.
- The project follows a one pull request per issue policy so you are expected to kindly follow the same.
- Please comment under the issues that you would want to work on to ask for assignment before working on them.

Kindly take note of the things listed. Happy hacking! 🥳

**Comment by DanBrown47** [comment]
Hi @t0xic0der, I have registered in the MLH Program, Thankx for the info and thanks for the advice, I`ll keep those in mind and Happy hacking !!

**Review by gridhead — CHANGES_REQUESTED** [review]
Good work done with the CODE_OF_CONDUCT.md and CONTRIBUTING.md @DanBrown47. This resolves #3. Please remove requirements.txt for now and add it via another PR as that resolves #4. Addressing two issues via one pull request violates our one pull request per issue policy. 

Keep it up! 👍

**Review by DanBrown47 — COMMENTED** [review]
The changes were made

**Review by gridhead — APPROVED** [review]
Looks good to me. I especially love the work that you did with CONTRIBUTING.md. :smile:

**Pull request merged**
